# Generated by Django 4.1.7 on 2023-03-06 10:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Tickets", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="Saldo",
            new_name="Balance",
        ),
    ]
